version: '3'
# run three services
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3000:3000"
  
  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3001:3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3002:3000"


# run the services
# docker-compose up --build
# -d to run the services in the background

# stop the services
# docker-compose down


# if you go to the inspect tab  in the localhoset:8080 you will see that the server is ngninx and it is powered by express, this means that the requests are going through nginx.
# though if you where the docker containers are running you will see no server in the network, meaning that the requests are going directly to where the container is running.
# but this take us to the next steps.
# instead of exposing all the applications. the three of the running applications should not be exposed to the public, this in production we wil open only the port 8080 in our case or whereever our nginx server is listents to
# all the other ports will not be publicly accessible.
# thats how it should work.