version: '3'
# run three services
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3000:3000"
  
  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3001:3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3002:3000"


# run the services
# docker-compose up --build
# -d to run the services in the background

# stop the services
# docker-compose down


